In [1]:
#Creamos el dataframe
import pandas as pd
df = pd.read_csv("country_vaccinations_by_manufacturer.csv")

           location        date          vaccine  total_vaccinations
0             Chile  2020-12-24  Pfizer/BioNTech                 420
1             Chile  2020-12-25  Pfizer/BioNTech                5198
2             Chile  2020-12-26  Pfizer/BioNTech                8338
3             Chile  2020-12-27  Pfizer/BioNTech                8649
4             Chile  2020-12-28  Pfizer/BioNTech                8649
...             ...         ...              ...                 ...
2373  United States  2021-04-14          Moderna            86221076
2374  United States  2021-04-14  Pfizer/BioNTech           100891617
2375  United States  2021-04-15  Johnson&Johnson             7736781
2376  United States  2021-04-15          Moderna            87539652
2377  United States  2021-04-15  Pfizer/BioNTech           102877491

[2378 rows x 4 columns]

In [27]:
#Agrupo por paÃ­s
vacs_by_country = df.groupby('location').agg(list)
vacs_by_country.rename(columns={'total_vaccinations':'vaccinations_per_day'},inplace=True)
vacs_by_country

,date,vaccine,vaccinations_per_day
location,,,
Chile,"[2020-12-24, 2020-12-25, 2020-12-26, 2020-12-2...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[420, 5198, 8338, 8649, 8649, 8649, 8649, 8649..."
Czechia,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[1250, 3543, 6986, 10454, 11759, 12019, 13268,..."
Germany,"[2020-12-27, 2020-12-27, 2020-12-27, 2020-12-2...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 24296, 0, 0, 42679, 0, 0, 91661, 0, 0, ..."
Iceland,"[2020-12-29, 2020-12-29, 2020-12-29, 2020-12-3...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 2525, 0, 0, 4941, 0, 0, 4941, 0, 0, 494..."
Italy,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[7169, 8590, 9595, 14322, 39798, 50852, 89362,..."
Latvia,"[2020-12-28, 2020-12-29, 2020-12-30, 2021-01-0...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[596, 1469, 2260, 2959, 3848, 4624, 5433, 6339..."
Lithuania,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[2420, 5207, 8194, 9726, 9751, 9752, 10375, 13..."
Romania,"[2020-12-27, 2020-12-27, 2020-12-27, 2020-12-2...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 965, 0, 0, 2066, 0, 0, 2778, 0, 0, 5666..."
United States,"[2021-01-12, 2021-01-12, 2021-01-13, 2021-01-1...","[Moderna, Pfizer/BioNTech, Moderna, Pfizer/Bio...","[3835859, 5488697, 4249795, 6025872, 5122662, ..."

In [28]:
#Creo la columna total de vacunados y ordeno
vacs_by_country['total_vaccinations'] = vacs_by_country['vaccinations_per_day'].apply(sum)
vacs_by_country

,date,vaccine,vaccinations_per_day,total_vaccinations
location,,,,
Chile,"[2020-12-24, 2020-12-25, 2020-12-26, 2020-12-2...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[420, 5198, 8338, 8649, 8649, 8649, 8649, 8649...",441997608
Czechia,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[1250, 3543, 6986, 10454, 11759, 12019, 13268,...",84387581
Germany,"[2020-12-27, 2020-12-27, 2020-12-27, 2020-12-2...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 24296, 0, 0, 42679, 0, 0, 91661, 0, 0, ...",732007653
Iceland,"[2020-12-29, 2020-12-29, 2020-12-29, 2020-12-3...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 2525, 0, 0, 4941, 0, 0, 4941, 0, 0, 494...",3810806
Italy,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[7169, 8590, 9595, 14322, 39798, 50852, 89362,...",529272173
Latvia,"[2020-12-28, 2020-12-29, 2020-12-30, 2021-01-0...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[596, 1469, 2260, 2959, 3848, 4624, 5433, 6339...",6361167
Lithuania,"[2020-12-27, 2020-12-28, 2020-12-29, 2020-12-3...","[Pfizer/BioNTech, Pfizer/BioNTech, Pfizer/BioN...","[2420, 5207, 8194, 9726, 9751, 9752, 10375, 13...",25608717
Romania,"[2020-12-27, 2020-12-27, 2020-12-27, 2020-12-2...","[Moderna, Oxford/AstraZeneca, Pfizer/BioNTech,...","[0, 0, 965, 0, 0, 2066, 0, 0, 2778, 0, 0, 5666...",159718596
United States,"[2021-01-12, 2021-01-12, 2021-01-13, 2021-01-1...","[Moderna, Pfizer/BioNTech, Moderna, Pfizer/Bio...","[3835859, 5488697, 4249795, 6025872, 5122662, ...",7849710124

In [29]:
#Muestro los datos que nos interesan ordenados
vacs_by_country_ordered = vacs_by_country[['total_vaccinations']].reset_index().sort_values(by='total_vaccinations',ascending=False)
vacs_by_country_ordered

        location  total_vaccinations
8  United States          7849710124
2        Germany           732007653
4          Italy           529272173
0          Chile           441997608
7        Romania           159718596
1        Czechia            84387581
6      Lithuania            25608717
5         Latvia             6361167
3        Iceland             3810806

In [48]:
#Muestro lo que pide la consigna
vacs_by_country_ordered.head(1)

        location  total_vaccinations
8  United States          7849710124