##  Parcialito X

El equipo comercial en Argentina de instagram cuenta con información sumarizada de usuarios del país en el siguiente Data Frame (id_usuario, nickname, país, fecha_alta, cantidad_seguidores, cantidad_seguidos, cantidad_total_publicaciones). 
Uno de sus analistas quiere obtener los potenciales 10 usuarios “influencers” que van a liderar su primera campaña de vía pública en el país y para ello necesita de nuestra ayuda. El criterio para detectar un influencer es que el mismo debe: 
- Tener una cantidad de seguidores mayor al 80% de la máxima cantidad de seguidores de todos los usuarios dentro de su país. (Por ejemplo, si un usuario es Argentino y el máximo de seguidores en Argentina es 1000 entonces requerirá tener al menos 800 seguidores).
- El número de usuarios que esa persona sigue no debe superar el 15% de la cantidad de seguidores que él tiene.
El criterio final para seleccionar a los candidatos será a partir de la mayor cantidad de seguidores que tengan. 

Escribir un programa en python Pandas que pueda obtener esos usuarios

In [42]:
# importacion general de librerias y de visualizacion (matplotlib y seaborn)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random as rd
%matplotlib inline

plt.style.use('default') # haciendo los graficos un poco mas bonitos en matplotlib
#plt.rcParams['figure.figsize'] = (20, 10)

sns.set(style="whitegrid") # seteando tipo de grid en seaborn

pd.options.display.float_format = '{:20,.2f}'.format # suprimimos la notacion cientifica en los outputs

import warnings
warnings.filterwarnings('ignore')

In [43]:
df = pd.DataFrame({
'id_usuario': range(1,21),
 'nickname': ['user'+str(element) for element in list(range(1,21))],
 'país': rd.choices(['Argentina','Brasil','Chile','Paraguay','Peru'],k=20),
 'fecha_alta': pd.date_range(start='2020-01-01',freq='D',periods=20),
 'cantidad_seguidores': rd.choices(range(100,1000),k=20),
 'cantidad_seguidos': rd.choices(range(0,300),k=20),
 'cantidad_total_publicaciones': rd.choices(range(1,100),k=20)
})
df

,id_usuario,nickname,país,fecha_alta,cantidad_seguidores,cantidad_seguidos,cantidad_total_publicaciones
0,1,user1,Argentina,2020-01-01,210,150,7
1,2,user2,Paraguay,2020-01-02,146,264,29
2,3,user3,Chile,2020-01-03,978,20,3
3,4,user4,Brasil,2020-01-04,510,28,93
4,5,user5,Chile,2020-01-05,882,268,71
5,6,user6,Argentina,2020-01-06,791,59,60
6,7,user7,Paraguay,2020-01-07,983,185,41
7,8,user8,Paraguay,2020-01-08,719,243,28
8,9,user9,Paraguay,2020-01-09,166,253,75
9,10,user10,Argentina,2020-01-10,843,37,59
10,11,user11,Brasil,2020-01-11,217,299,24
11,12,user12,Brasil,2020-01-12,901,161,39
12,13,user13,Chile,2020-01-13,141,91,69
13,14,user14,Paraguay,2020-01-14,799,98,67
14,15,user15,Paraguay,2020-01-15,542,96,1
15,16,user16,Paraguay,2020-01-16,750,33,83
16,17,user17,Chile,2020-01-17,736,168,6
17,18,user18,Argentina,2020-01-18,417,268,89
18,19,user19,Paraguay,2020-01-19,678,111,42
19,20,user20,Argentina,2020-01-20,478,10,10

Primero obtengo por país los seguidores

In [44]:
df['max_seguidores_pais'] = df.groupby('país')['cantidad_seguidores'].transform('max')
df = df[['nickname','país','cantidad_seguidores','cantidad_seguidos','max_seguidores_pais']]
df

,nickname,país,cantidad_seguidores,cantidad_seguidos,max_seguidores_pais
0,user1,Argentina,210,150,843
1,user2,Paraguay,146,264,983
2,user3,Chile,978,20,978
3,user4,Brasil,510,28,901
4,user5,Chile,882,268,978
5,user6,Argentina,791,59,843
6,user7,Paraguay,983,185,983
7,user8,Paraguay,719,243,983
8,user9,Paraguay,166,253,983
9,user10,Argentina,843,37,843
10,user11,Brasil,217,299,901
11,user12,Brasil,901,161,901
12,user13,Chile,141,91,978
13,user14,Paraguay,799,98,983
14,user15,Paraguay,542,96,983
15,user16,Paraguay,750,33,983
16,user17,Chile,736,168,978
17,user18,Argentina,417,268,843
18,user19,Paraguay,678,111,983
19,user20,Argentina,478,10,843

In [46]:
mask_pais = df['cantidad_seguidores']/df['max_seguidores_pais'] >= 0.8
mask_seguidos = df['cantidad_seguidos']/df['cantidad_seguidores'] < 0.15
df.loc[ mask_pais&mask_seguidos,:].nlargest(10,'cantidad_seguidores')['nickname']

2      user3
9     user10
13    user14
5      user6
Name: nickname, dtype: object