In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

/home/alexis/.local/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
oscars_short = pd.read_csv('Oscars-demographics-DFE.csv', encoding='latin-1',\
                usecols=['birthplace', 'date_of_birth', 'race_ethnicity', 'religion','sexual_orientation', 'year_of_award', 'award', 'movie', 'person'])
oscars_short.tail(20)

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
421,"Los Angeles, Ca",4-Jun-75,White,Buddhist,Bisexual,2000,Best Supporting Actress,"Girl, Interrupted",Angelina Jolie
422,New York City,31-Oct-27,White,Jewish,Straight,1976,Best Supporting Actress,Shampoo,Lee Grant
423,New York City,25-Jun-1903,White,Na,Straight,1946,Best Supporting Actress,National Velvet,Anne Revere
424,"Bascom, Fl",14-Jan-41,White,Roman Catholic,Straight,1977,Best Actress,Network,Faye Dunaway
425,"Walters, Ok",13-Dec-10,White,Na,Straight,1943,Best Supporting Actor,Johnny Eager,Van Heflin
426,"Thomasville, Ga",27-Feb-30,White,Na,Straight,1958,Best Actress,The Three Faces of Eve,Joanne Woodward
427,"Helena, Mt",7-May-1901,White,Roman Catholic,Straight,1953,Best Actor,High Noon,Gary Cooper
428,"London, England",27-Feb-32,White,Jewish,Straight,1967,Best Actress,Who's Afraid of Virginia Woolf?,Elizabeth Taylor
429,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
430,"Lincoln, Ne",30-Jul-74,White,Na,Straight,2005,Best Actress,Million Dollar Baby,Hilary Swank
431,"Los Angeles, Ca",27-Sep-72,White,Jewish,Straight,1999,Best Actress,Shakespeare in Love,Gwyneth Paltrow
432,"Malden, Ma",16-Jun-07,White,Na,Na,1969,Best Supporting Actor,The Subject Was Roses,Jack Albertson
433,"Woodlawn, Md",11-Dec-67,Black,Na,Straight,2010,Best Supporting Actress,Precious,Mo'Nique
434,"La Jolla, Ca",14-Aug-59,White,Na,Straight,2001,Best Supporting Actress,Pollock,Marcia Gay Harden
435,"Ilford, Essex, England",28-Dec-34,White,Na,Straight,1970,Best Actress,The Prime of Miss Jean Brodie,Maggie Smith
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [3]:
oscars_demographics = pd.read_csv('Oscars-demographics-DFE.csv', encoding='latin-1')
oscars_demographics.tail()

,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,award,biourl,birthplace_gold,date_of_birth_gold,movie,person,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
436,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,Rachel Weisz,NaN,NaN,NaN,NaN
437,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,Danny Boyle,NaN,NaN,NaN,NaN
438,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,Jason Robards,NaN,NaN,NaN,NaN
439,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,James Coburn,NaN,NaN,NaN,NaN
440,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,John Huston,NaN,NaN,NaN,NaN

In [4]:
oscars_demographics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441 entries, 0 to 440
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _unit_id                       441 non-null    int64
 1   _golden                        441 non-null    bool
 2   _unit_state                    441 non-null    object
 3   _trusted_judgments             441 non-null    int64
 4   _last_judgment_at              416 non-null    object
 5   birthplace                     441 non-null    object
 6   birthplace:confidence          441 non-null    float64
 7   date_of_birth                  441 non-null    object
 8   date_of_birth:confidence       441 non-null    float64
 9   race_ethnicity                 441 non-null    object
 10  race_ethnicity:confidence      441 non-null    float64
 11  religion                       441 non-null    object
 12  religion:confidence            441 non-null    float64
 13  sexual_orientation             441 non-null    object
 14  sexual_orientation:confidence  441 non-null    float64
 15  year_of_award                  441 non-null    int64
 16  year_of_award:confidence       441 non-null    float64
 17  award                          441 non-null    object
 18  biourl                         441 non-null    object
 19  birthplace_gold                9 non-null      object
 20  date_of_birth_gold             8 non-null      object
 21  movie                          441 non-null    object
 22  person                         441 non-null    object
 23  race_ethnicity_gold            2 non-null      object
 24  religion_gold                  10 non-null     object
 25  sexual_orientation_gold        3 non-null      object
 26  year_of_award_gold             11 non-null     float64
dtypes: bool(1), float64(7), int64(3), object(16)
memory usage: 90.1+ KB

In [5]:
oscars_demographics.describe()

,_unit_id,_trusted_judgments,birthplace:confidence,date_of_birth:confidence,race_ethnicity:confidence,religion:confidence,sexual_orientation:confidence,year_of_award,year_of_award:confidence,year_of_award_gold
count,4.410000e+02,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,441.000000,11.000000
mean,6.704825e+08,7.637188,0.995259,0.996607,0.999130,0.989373,0.992390,1973.165533,0.990082,1977.363636
std,1.139974e+05,19.015541,0.038917,0.032060,0.016438,0.065610,0.049458,24.030895,0.059177,21.592928
min,6.704544e+08,3.000000,0.657100,0.656200,0.657100,0.333300,0.657100,1927.000000,0.333300,1942.000000
25%,6.704545e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1953.000000,1.000000,1964.000000
50%,6.704546e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1973.000000,1.000000,1977.000000
75%,6.704547e+08,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1994.000000,1.000000,1997.000000
max,6.709729e+08,95.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2014.000000,1.000000,2006.000000

In [6]:
oscars_index = oscars_demographics.index
oscars_columns = oscars_demographics.columns
oscars_data = oscars_demographics.values

In [7]:
type(oscars_index)

pandas.core.indexes.range.RangeIndex

In [8]:
oscars_columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'birthplace', 'birthplace:confidence',
       'date_of_birth', 'date_of_birth:confidence', 'race_ethnicity',
       'race_ethnicity:confidence', 'religion', 'religion:confidence',
       'sexual_orientation', 'sexual_orientation:confidence', 'year_of_award',
       'year_of_award:confidence', 'award', 'biourl', 'birthplace_gold',
       'date_of_birth_gold', 'movie', 'person', 'race_ethnicity_gold',
       'religion_gold', 'sexual_orientation_gold', 'year_of_award_gold'],
      dtype='object')

In [9]:
type(oscars_data)

numpy.ndarray

In [10]:
oscars_demographics['religion']

0                  Na
1                  Na
2                  Na
3                  Na
4      Roman Catholic
            ...
436            Jewish
437    Roman Catholic
438                Na
439                Na
440                Na
Name: religion, Length: 441, dtype: object

In [11]:
oscars_movie = oscars_demographics['movie']

In [12]:
oscars_movie.value_counts(normalize=True)

Million Dollar Baby       0.011338
West Side Story           0.009070
Network                   0.009070
Cabaret                   0.006803
No Country for Old Men    0.006803
                            ...
Dead Man Walking          0.002268
The Trip to Bountiful     0.002268
Places in the Heart       0.002268
Bullets Over Broadway     0.002268
Ed Wood                   0.002268
Name: movie, Length: 336, dtype: float64

In [13]:
oscars_date_of_birth_gold = oscars_demographics['date_of_birth_gold']
oscars_date_of_birth_gold

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
436    NaN
437    NaN
438    NaN
439    NaN
440    NaN
Name: date_of_birth_gold, Length: 441, dtype: object

In [14]:
oscars_date_of_birth_gold_fillna = oscars_date_of_birth_gold.fillna('None')
oscars_date_of_birth_gold_fillna.describe()

count      441
unique       9
top       None
freq       433
Name: date_of_birth_gold, dtype: object

In [15]:
oscars_date_of_birth_gold_dropna = oscars_date_of_birth_gold.dropna()
oscars_date_of_birth_gold_dropna

21      5-Aug-06
33     22-Jun-06
152     9-Jul-56
205    16-Jun-07
263    16-Jul-11
280    27-Feb-30
377    31-Oct-27
411    11-Dec-67
Name: date_of_birth_gold, dtype: object

In [16]:
oscars_demographics._trusted_judgments.min(),oscars_demographics._trusted_judgments.max(),oscars_demographics._trusted_judgments.mean(),oscars_demographics._trusted_judgments.median(),oscars_demographics._trusted_judgments.std(),oscars_demographics._trusted_judgments.sum()

(3, 95, 7.63718820861678, 3.0, 19.015540899806773, 3368)

In [17]:
(oscars_demographics.year_of_award==1969).value_counts()

False    433
True       8
Name: year_of_award, dtype: int64

In [18]:
oscars_demographics['year_of_award_gold'].isnull().mean()

0.9750566893424036

In [19]:
oscars = oscars_demographics[['birthplace',
       'date_of_birth', 'race_ethnicity', 'religion',
       'sexual_orientation', 'year_of_award', 'award', 'movie', 'person']]

In [21]:
print(len(oscars))
oscars = oscars.dropna()
print(len(oscars))

441
441

In [22]:
oscars.tail()

,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
436,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
437,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
438,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
439,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
440,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston

In [23]:
oscars.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 441 entries, 0 to 440
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   birthplace          441 non-null    object
 1   date_of_birth       441 non-null    object
 2   race_ethnicity      441 non-null    object
 3   religion            441 non-null    object
 4   sexual_orientation  441 non-null    object
 5   year_of_award       441 non-null    int64
 6   award               441 non-null    object
 7   movie               441 non-null    object
 8   person              441 non-null    object
dtypes: int64(1), object(8)
memory usage: 34.5+ KB

In [26]:
oscars_byID=oscars.set_index(['person','year_of_award'])
oscars_byID.tail()

,,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,award,movie
person,year_of_award,,,,,,,
Rachel Weisz,2006,"London, England",7-Mar-71,White,Jewish,Straight,Best Supporting Actress,The Constant Gardener
Danny Boyle,2009,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,Best Director,Slumdog Millionaire
Jason Robards,1977,"Chicago, Il",26-Jul-22,White,Na,Straight,Best Supporting Actor,All the President's Men
James Coburn,1999,"Laurel, Ne",31-Aug-28,White,Na,Straight,Best Supporting Actor,Affliction
John Huston,1949,"Nevada, Mo",5-Aug-06,White,Na,Straight,Best Director,The Treasure of the Sierra Madre

In [25]:
oscars_byID = pd.read_csv('Oscars-demographics-DFE.csv', encoding='latin-1', index_col=['person','year_of_award'])
oscars_byID.tail()

,,_unit_id,_golden,_unit_state,_trusted_judgments,_last_judgment_at,birthplace,birthplace:confidence,date_of_birth,date_of_birth:confidence,race_ethnicity,...,year_of_award:confidence,award,biourl,birthplace_gold,date_of_birth_gold,movie,race_ethnicity_gold,religion_gold,sexual_orientation_gold,year_of_award_gold
person,year_of_award,,,,,,,,,,,,,,,,,,,,,
Rachel Weisz,2006,670946276,False,finalized,3,2/10/15 2:00,"London, England",1.0,7-Mar-71,1.0,White,...,0.6857,Best Supporting Actress,http://www.nndb.com/people/309/000032213/,NaN,NaN,The Constant Gardener,NaN,NaN,NaN,NaN
Danny Boyle,2009,670946299,False,finalized,3,2/10/15 2:04,"Manchester, England",1.0,20-Oct-56,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/887/000044755/,NaN,NaN,Slumdog Millionaire,NaN,NaN,NaN,NaN
Jason Robards,1977,670964912,False,finalized,3,2/10/15 2:03,"Chicago, Il",1.0,26-Jul-22,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/224/000032128/,NaN,NaN,All the President's Men,NaN,NaN,NaN,NaN
James Coburn,1999,670964956,False,finalized,3,2/10/15 2:01,"Laurel, Ne",1.0,31-Aug-28,1.0,White,...,1.0000,Best Supporting Actor,http://www.nndb.com/people/764/000022698/,NaN,NaN,Affliction,NaN,NaN,NaN,NaN
John Huston,1949,670972898,False,finalized,3,2/10/15 2:01,"Nevada, Mo",1.0,5-Aug-06,1.0,White,...,1.0000,Best Director,http://www.nndb.com/people/704/000024632/,NaN,NaN,The Treasure of the Sierra Madre,NaN,NaN,NaN,NaN

In [28]:
oscars_byID.reset_index()

,person,year_of_award,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,award,movie
0,Lewis Milestone,1927,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,Best Director,Two Arabian Knights
1,Frank Lloyd,1930,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,Best Director,The Divine Lady
2,Lewis Milestone,1931,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,Best Director,All Quiet on the Western Front
3,Norman Taurog,1932,"Chicago, Il",23-Feb-1899,White,Na,Straight,Best Director,Skippy
4,Frank Borzage,1933,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,Best Director,Bad Girl
...,...,...,...,...,...,...,...,...,...
436,Rachel Weisz,2006,"London, England",7-Mar-71,White,Jewish,Straight,Best Supporting Actress,The Constant Gardener
437,Danny Boyle,2009,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,Best Director,Slumdog Millionaire
438,Jason Robards,1977,"Chicago, Il",26-Jul-22,White,Na,Straight,Best Supporting Actor,All the President's Men
439,James Coburn,1999,"Laurel, Ne",31-Aug-28,White,Na,Straight,Best Supporting Actor,Affliction
440,John Huston,1949,"Nevada, Mo",5-Aug-06,White,Na,Straight,Best Director,The Treasure of the Sierra Madre

In [30]:
oscars_byID=oscars.set_index(['person','year_of_award'],drop=False)
oscars_byID

,,birthplace,date_of_birth,race_ethnicity,religion,sexual_orientation,year_of_award,award,movie,person
person,year_of_award,,,,,,,,,
Lewis Milestone,1927,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1927,Best Director,Two Arabian Knights,Lewis Milestone
Frank Lloyd,1930,"Glasgow, Scotland",2-Feb-1886,White,Na,Straight,1930,Best Director,The Divine Lady,Frank Lloyd
Lewis Milestone,1931,"Chisinau, Moldova",30-Sep-1895,White,Na,Straight,1931,Best Director,All Quiet on the Western Front,Lewis Milestone
Norman Taurog,1932,"Chicago, Il",23-Feb-1899,White,Na,Straight,1932,Best Director,Skippy,Norman Taurog
Frank Borzage,1933,"Salt Lake City, Ut",23-Apr-1894,White,Roman Catholic,Straight,1933,Best Director,Bad Girl,Frank Borzage
...,...,...,...,...,...,...,...,...,...,...
Rachel Weisz,2006,"London, England",7-Mar-71,White,Jewish,Straight,2006,Best Supporting Actress,The Constant Gardener,Rachel Weisz
Danny Boyle,2009,"Manchester, England",20-Oct-56,White,Roman Catholic,Straight,2009,Best Director,Slumdog Millionaire,Danny Boyle
Jason Robards,1977,"Chicago, Il",26-Jul-22,White,Na,Straight,1977,Best Supporting Actor,All the President's Men,Jason Robards
James Coburn,1999,"Laurel, Ne",31-Aug-28,White,Na,Straight,1999,Best Supporting Actor,Affliction,James Coburn
John Huston,1949,"Nevada, Mo",5-Aug-06,White,Na,Straight,1949,Best Director,The Treasure of the Sierra Madre,John Huston